  version: '3.8'
  volumes:
    redis_data:
  services:
    redis:
      image: redis:alpine
      command: redis-server
      ports:
        - target: 6379
          published: 6379
          protocol: tcp
          mode: host
      volumes:
          - redis_data:/data
      restart: always
      environment:
        - REDIS_REPLICATION_MODE=maste